# Run configuration
Run_Name : "HIV_test"
Sample_Info : "etc/tests/test.hiv.csv" # Must be absolute path OR relative to chiva installation directory
Supplemental_Info : ""
Processing_Path : "etc/tests"
Ref_Genome : "hg38"
Ref_Genome_Path : "genomes/hg38.2bit"
Viral_Genomes : "genomes/viral_genomes"
Aligner : "blat"

# Sequence files
Seq_Path : "etc/tests/Data/"
R1: "Undetermined_S0_L001_R1_001.fastq.gz"
R2: "Undetermined_S0_L001_R2_001.fastq.gz"
I1: "Undetermined_S0_L001_I1_001.fastq.gz"

# SampleInfo formating
Sample_Name_Column : "sampleName"

# Sequence information
R1_Leading_Trim : "sampleInfo:barcode1"
R1_Overreading_Trim : "sampleInfo:R1Over"
R2_Primer_Seq : "sampleInfo:primer"
R2_LTRBit_Seq : "sampleInfo:LTR"
R2_Overreading_Trim : "AGTCCCTTAAGCGGAG"
Require_TermCA : "CA"

# ------------------------------------------------------------------------------
# Pipeline configuration settings
Read_Types : ["R1", "R2", "I1"]
Genomic_Reads : ["R1", "R2"]

# Memory Management (in MB units)
demultiMB : 16000
trimMB : 4000
filtMB : 4000
consolMB : 4000
alignMB : 4000
coupleMB : 4000
processMB : 4000
reportMB : 4000

# Demultiplexing parameters
barcode1Length : 20
barcode2Length : 12
barcode1 : "R1"
barcode2 : "I1"
bc1Mismatch : 3
bc2Mismatch : 1
maxNcount : 1

# Sequence trimming
## R1 sequence
R1leadMismatch : "3 2"
R1overMismatch : 2
R1overLength : 20
## R2 sequence
R2primerMismatch : 0
R2bitMismatch : 12
R2overMismatch : 2
R2overMaxLength : 20

# Reference Alignment
BLATparams : "-tileSize=11 -stepSize=9 -minIdentity=85 -maxIntron=5 -minScore=27 -dots=1000 -out=psl -noHead"

# Post-alignment filtering
maxAlignStart : 5
minPercentIdentity : 95
minTempLength : 30
maxTempLength : 2500

# Internal fragment positive selection filtering
ifAlignType : "lg"
ifPctID : 75
ifPctIDType : "local"
ifSubMatAdj : "iAR"
ifGapOpen : 2
ifGapExt : 0
ifMinAlignLength : 20

# Post-processing
refGenes : 
    file : "genomes/hg38.refSeq.ext.nomodel.rds"
    symbolCol : "name2"
oncoGeneList : 
    file : "http://bushmanlab.org/assets/doc/allOnco_Feb2017.tsv"
    symbolCol : "symbol"
specialGeneList : 
    file : "http://bushmanlab.org/assets/doc/humanLymph.tsv"
    symbolCol : "symbol"

# Report
suppFile : FALSE
figures : TRUE
reportData : FALSE
reportFormat : "html"
signature : "Christopher L. Nobles, Ph.D. [Bushman Lab]"
