# Run configuration
Run_Name : "HIV_test"
Sample_Info : "etc/tests/test.hiv.csv"
Supplemental_Info : ""
Processing_Path : "etc/tests"
Ref_Genome : "hg38"
Ref_Genome_Path : "/home/nobles/data/genomes/hg38/hg38.2bit"
Aligner : "blat"

# Sequence files
R1: "etc/tests/Data/Undetermined_S0_L001_R1_001.fastq.gz"
R2: "etc/tests/Data/Undetermined_S0_L001_R2_001.fastq.gz"
I1: "etc/tests/Data/Undetermined_S0_L001_I1_001.fastq.gz"

# SampleInfo formating
Sample_Name_Column : "sampleName"

# Sequence information
R1_Leading_Trim : "sampleInfo:barcode1"
R1_Overreading_Trim : "sampleInfo:R1Over"
R2_Primer_Seq : "sampleInfo:primer"
R2_LTRBit_Seq : "sampleInfo:LTR"
R2_Overreading_Trim : "AGTCCCTTAAGCGGAG"
Require_TermCA : "CA"

# ------------------------------------------------------------------------------
# Pipeline configuration settings
Read_Types : ["R1", "R2", "I1"]
Genomic_Reads : ["R1", "R2"]

# Demultiplexing parameters
barcode1Length : 20
barcode2Length : 12
barcode1 : "R1"
barcode2 : "I1"
bc1Mismatch : 3
bc2Mismatch : 1
demultiCores : 4
demultiMb : 30000

# Sequence trimming
## R1 sequence
R1leadMismatch : "3 2"
R1overMismatch : 2
R1overLength : 20
## R2 sequence
R2primerMismatch : 0
R2bitMismatch : 12
R2overMismatch : 2
R2overMaxLength : 20
trimMb : 5000

# Consolidation of sequences
consolMb : 5000

# Reference Alignment
BLATparams : "-tileSize=11 -stepSize=9 -minIdentity=85 -maxIntron=5 -minScore=27 -dots=1000 -out=psl -noHead"
BLATMb : 5000

# Post-alignment filtering
maxAlignStart : 5
minPercentIdentity : 95
minTempLength : 30
maxTempLength : 2500
coupleMb : 5000

# Post-processing
refGenes : 
    file : "/home/nobles/data/util_files/hg38.refSeq.rds"
    symbolCol : "name2"
oncoGeneList : 
    file : "http://bushmanlab.org/assets/doc/allOnco_Feb2017.tsv"
    symbolCol : "symbol"
specialGeneList : 
    file : "http://bushmanlab.org/assets/doc/humanLymph.tsv"
    symbolCol : "symbol"

# Report
suppFile : FALSE
figures : TRUE
reportData : FALSE
reportFormat : "html"
signature : "Christopher L. Nobles, Ph.D. [Bushman Lab]"
